### ISSUE TITLE
关于mybox

### ISSUE THREAD

**Issue by mapleftian** [digglife/maoyan-font#2]
请问win下应该怎么使用mybox的？

**Comment by digglife** [comment]
Windows 下也是一样的。如果 Python 的安装路径 是`C:\Users\mapleftian\AppData\Local\Programs\Python\Python37`，那么所有第三方可执行命令都会安装在这个路径的 `Scripts` 目录下，你可以切换到这个目录去执行 `mybox`，但最好是将这个路径(`C:\Users\mapleftian\AppData\Local\Programs\Python\Python37\Scripts`)加入到环境变量`%PATH%`。

**Comment by digglife** [comment]
![image](https://user-images.githubusercontent.com/1468378/57266581-1a0a9680-70af-11e9-92a4-b6b1f383d05d.png)
